# Generated by Django 4.1.5 on 2023-10-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccordPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images')),
                ('chord', models.PositiveSmallIntegerField(choices=[(1, 'm7'), (2, 'm9'), (3, 'm11'), (4, '7'), (5, '9'), (6, '13'), (7, '7(#11)'), (8, '13(#11)'), (9, '7(b9)'), (10, '7(#9)'), (11, '7(b5)'), (12, '7(#5)'), (13, '7(b9, b5)'), (14, '7(#9, b5)'), (15, '7(b9,b13)'), (16, '7(#9,b13)'), (17, 'm7(b5)'), (18, 'm9(b5)'), (19, '7sus4'), (20, '9sus4'), (21, '13sus4'), (22, '6/9'), (23, 'maj7'), (24, 'maj9'), (25, 'maj7(#11)'), (26, 'min6/9'), (27, 'min(maj7)'), (28, 'min9(maj7)')])),
                ('music_key', models.CharField(choices=[('C', 'До'), ('Db', 'Ре бемоль'), ('D', 'Ре'), ('Eb', 'Ми бемоль'), ('E', 'Ми'), ('F', 'Фа'), ('F#', 'Фа диез'), ('G', 'Соль'), ('Ab', 'Ля бемоль'), ('A', 'Ля'), ('Bb', 'Си бемоль'), ('B', 'Си')], max_length=5)),
            ],
            options={
                'verbose_name': 'Нотный пример',
                'verbose_name_plural': 'Нотные примеры',
            },
        ),
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.FileField(upload_to='media')),
                ('chord', models.PositiveSmallIntegerField(choices=[(1, 'm7'), (2, 'm9'), (3, 'm11'), (4, '7'), (5, '9'), (6, '13'), (7, '7(#11)'), (8, '13(#11)'), (9, '7(b9)'), (10, '7(#9)'), (11, '7(b5)'), (12, '7(#5)'), (13, '7(b9, b5)'), (14, '7(#9, b5)'), (15, '7(b9,b13)'), (16, '7(#9,b13)'), (17, 'm7(b5)'), (18, 'm9(b5)'), (19, '7sus4'), (20, '9sus4'), (21, '13sus4'), (22, '6/9'), (23, 'maj7'), (24, 'maj9'), (25, 'maj7(#11)'), (26, 'min6/9'), (27, 'min(maj7)'), (28, 'min9(maj7)')])),
                ('music_key', models.CharField(choices=[('C', 'До'), ('Db', 'Ре бемоль'), ('D', 'Ре'), ('Eb', 'Ми бемоль'), ('E', 'Ми'), ('F', 'Фа'), ('F#', 'Фа диез'), ('G', 'Соль'), ('Ab', 'Ля бемоль'), ('A', 'Ля'), ('Bb', 'Си бемоль'), ('B', 'Си')], max_length=5)),
            ],
            options={
                'verbose_name': 'Аккорд',
                'verbose_name_plural': 'Аккорды',
            },
        ),
        migrations.CreateModel(
            name='ChordChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_time', models.DateTimeField(auto_now=True)),
                ('decision', models.PositiveSmallIntegerField(choices=[(1, 'm7'), (2, 'm9'), (3, 'm11'), (4, '7'), (5, '9'), (6, '13'), (7, '7(#11)'), (8, '13(#11)'), (9, '7(b9)'), (10, '7(#9)'), (11, '7(b5)'), (12, '7(#5)'), (13, '7(b9, b5)'), (14, '7(#9, b5)'), (15, '7(b9,b13)'), (16, '7(#9,b13)'), (17, 'm7(b5)'), (18, 'm9(b5)'), (19, '7sus4'), (20, '9sus4'), (21, '13sus4'), (22, '6/9'), (23, 'maj7'), (24, 'maj9'), (25, 'maj7(#11)'), (26, 'min6/9'), (27, 'min(maj7)'), (28, 'min9(maj7)')], verbose_name='Выберите аккорд:')),
                ('right_decision', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'm7'), (2, 'm9'), (3, 'm11'), (4, '7'), (5, '9'), (6, '13'), (7, '7(#11)'), (8, '13(#11)'), (9, '7(b9)'), (10, '7(#9)'), (11, '7(b5)'), (12, '7(#5)'), (13, '7(b9, b5)'), (14, '7(#9, b5)'), (15, '7(b9,b13)'), (16, '7(#9,b13)'), (17, 'm7(b5)'), (18, 'm9(b5)'), (19, '7sus4'), (20, '9sus4'), (21, '13sus4'), (22, '6/9'), (23, 'maj7'), (24, 'maj9'), (25, 'maj7(#11)'), (26, 'min6/9'), (27, 'min(maj7)'), (28, 'min9(maj7)')], null=True, verbose_name='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.studentmap')),
            ],
            options={
                'verbose_name': 'Угаданный аккорд',
                'verbose_name_plural': 'Угаданные аккорды',
                'ordering': ['-choice_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='chord',
            constraint=models.UniqueConstraint(fields=('chord', 'music_key'), name='Каждая запись аккорда в одной тональности один раз.'),
        ),
        migrations.AddConstraint(
            model_name='accordpicture',
            constraint=models.UniqueConstraint(fields=('chord', 'music_key'), name='Каждый нотный пример в одной тональности один раз.'),
        ),
    ]
