# Generated by Django 4.1.5 on 2023-02-25 12:48

from django.db import migrations, models
import django.db.models.deletion
import practice.Datamixins.Chordmixsin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0003_remove_studentmap_graduate_alter_feetback_stars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChordChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_time', models.DateTimeField(auto_now=True)),
                ('desigion', models.PositiveSmallIntegerField(choices=[(1, 'm7'), (2, 'm9'), (3, 'm11'), (4, '7'), (5, '9'), (6, '13'), (7, '7(#11)'), (8, '7(b9)'), (9, '7(#9)'), (10, '7(b5)'), (11, '7(#5)'), (12, '7(b9,b13)'), (13, '7(#9,b13)'), (14, 'm7(b5)'), (15, 'm9(b5)'), (16, '7sus4'), (17, '9sus4'), (18, '13sus4'), (19, 'maj7'), (20, 'maj9'), (21, 'maj7(#11)'), (22, 'min(maj7)'), (23, 'min9(maj7)'), (24, 'min6'), (25, 'min6/9')], verbose_name='Выберите аккорд:')),
                ('right_desigion', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'm7'), (2, 'm9'), (3, 'm11'), (4, '7'), (5, '9'), (6, '13'), (7, '7(#11)'), (8, '7(b9)'), (9, '7(#9)'), (10, '7(b5)'), (11, '7(#5)'), (12, '7(b9,b13)'), (13, '7(#9,b13)'), (14, 'm7(b5)'), (15, 'm9(b5)'), (16, '7sus4'), (17, '9sus4'), (18, '13sus4'), (19, 'maj7'), (20, 'maj9'), (21, 'maj7(#11)'), (22, 'min(maj7)'), (23, 'min9(maj7)'), (24, 'min6'), (25, 'min6/9')], null=True, verbose_name='Верное решение:')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.studentmap')),
            ],
            options={
                'ordering': ['-choice_time'],
            },
            bases=(models.Model, practice.Datamixins.Chordmixsin.ChordDataMixin),
        ),
    ]
