# Generated by Django 4.1.5 on 2023-03-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_alter_chordchoice_desigion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.FileField(upload_to='media')),
                ('chord', models.PositiveSmallIntegerField(choices=[(1, 'm7'), (2, 'm9'), (3, 'm11'), (4, '7'), (5, '9'), (6, '13'), (7, '7(#11)'), (8, '7(b9)'), (9, '7(#9)'), (10, '7(#5)'), (11, '7(b9,b13)'), (12, '7(#9,b13)'), (13, 'm7(b5)'), (14, 'm9(b5)'), (15, '7sus4'), (16, '9sus4'), (17, '13sus4'), (18, 'maj7'), (19, 'maj9'), (20, 'maj7(#11)'), (21, 'min(maj7)'), (22, 'min9(maj7)'), (23, 'min6'), (24, 'min6/9')])),
            ],
        ),
    ]
