# Generated by Django 4.1.5 on 2023-01-26 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='О сайте')),
                ('page', models.PositiveSmallIntegerField(verbose_name='Страничка')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalMap',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('stady_level', models.PositiveSmallIntegerField(choices=[(0, 'Не выбранно'), (1, 'Нет музыкального образования'), (2, 'Музыкальная школа'), (3, 'Среднее музыкальное образование'), (4, 'Бакалавриат'), (5, 'Магистратура'), (6, 'Аспирантура')], default=0, verbose_name='Уровень образования')),
                ('stady_course', models.PositiveSmallIntegerField(choices=[(0, 'Нет музыкального образования'), (1, '1й'), (2, '2й'), (3, '3й'), (4, '4й'), (5, '5й')], default=0, verbose_name='Курс')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMap',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('reiting', models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('start_study', models.DateTimeField(auto_now=True, verbose_name='Начало обучения')),
                ('graduate', models.BooleanField(default=False, verbose_name='Закончил курс')),
            ],
        ),
    ]
