# Generated by Django 4.1.5 on 2023-02-04 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsite',
            options={'ordering': ['page']},
        ),
        migrations.AlterModelOptions(
            name='studentmap',
            options={'ordering': ['-reiting']},
        ),
        migrations.AlterField(
            model_name='personalmap',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='О себе'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalmap',
            name='stady_course',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не выбранно'), (1, '1й'), (2, '2й'), (3, '3й'), (4, '4й'), (5, '5й')], default=0, verbose_name='Курс'),
        ),
        migrations.CreateModel(
            name='Feetback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], verbose_name='Оценка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_time'],
            },
        ),
    ]
