# Generated by Django 4.1.5 on 2023-02-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_aboutsite_options_alter_studentmap_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmap',
            name='graduate',
        ),
        migrations.AlterField(
            model_name='feetback',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='feetback',
            name='text',
            field=models.TextField(verbose_name=''),
        ),
    ]
