# Generated by Django 4.1.5 on 2023-04-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_remove_studentmap_graduate_alter_feetback_stars_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsite',
            options={'ordering': ['page'], 'verbose_name': 'Описание сайта', 'verbose_name_plural': 'Описание сайта'},
        ),
        migrations.AlterModelOptions(
            name='feetback',
            options={'ordering': ['-pub_time'], 'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='personalmap',
            options={'verbose_name': 'Персональная карта', 'verbose_name_plural': 'Персональные карты'},
        ),
        migrations.AlterModelOptions(
            name='studentmap',
            options={'ordering': ['-reiting'], 'verbose_name': 'Карта студента', 'verbose_name_plural': 'Карты студентов'},
        ),
        migrations.AddField(
            model_name='studentmap',
            name='activiti',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Активность практики'),
        ),
    ]
